export enum MediaStatusEnum {
  IN_PRODUCTION = "In Production",
  RELEASED = "Released",
  POST_PRODUCTION = "Post Production",
  ON_HOLD = "On Hold",
  CANCELED = "Canceled",
}

export enum MediaGenriesEnum {
  ACTION = "Action",
  DRAMA = "Drama",
  COMEDY = "Comedy",
  FASTASY = "Fantasy",
  HORROR = "Horror",
  ROMANCE = "Romance",
  ADVANTURE = "Aventure",
  WAR = "War",
  BIO_GRAPHY = "Biography",
  SUPER_HERO = "Super Hero",
}

export enum MediaCountriesEnum {
  USA = "United States of America",
  AUSTRALIA = "Australia",
  AUSTRIA = "Austria",
  AFGHANISTAN = "Afghanistan",
  CANADA = "Canada",
  CHINA = "China",
  REPUBLIC_OF_CHINA = "Republic of China",
  FRANCE = "France",
  GERMANY = "Germany",
  INDIA = "India",
  INDONESIA = "Indonesia",
  IRAN = "Iran",
  IRAQ = "Iraq",
  ITALY = "Italy",
  JAPAN = "Japan",
  NORTH_KOREA = "North korea",
  SOUTH_KOREA = "South korea",
  MEXICO = "Mexico",
  NETHERLANDS = "Netherlands",
  NEW_ZEALAND = "New zealand",
  PAKISTAN = "Pakistan",
  RUSSIAN_FEDERATION = "Russian Federation",
  SINGAPORE = "Singapore",
  SPAIN = "Spain",
  SWITZERLAND = "Switzer land",
  THAILAND = "Thailand",
  TURKEY = "Turkey",
  UNITED_KINGDOM = "United kingdom",
  YEMEN = "Yemen",
  ZIMBABWE = "Zimbabwe",
}

export enum MediaLanguagiesEnum {
  ENGLISH = "English",
  GERMAN = "German",
  PERSIAN = "Persian",
  CHINESE = "Chinese",
  FRENCH = "French",
  HINDI = "Hindi",
  INDONESIAN = "Indonesian",
  ARABIC = "Arabic",
  ITALIAN = "Italian",
  JAPANESE = "Japanese",
  KOREAN = "Korean",
  SPANISH = "Spanish",
  DUTCH = "Dutch",
  URDU = "Urdu",
  RUSSIAN = "Rassian",
  THAI = "Thai",
  TURKISH = "Turkish",
}
